# basic options
title: CSE1017 프로그래밍기초
author: 도경구
email: doh@hanyang.ac.kr
description: 한양대학교 ERICA 소프트웨어융합대학 2019년 1학기
twitter_username:
github_username: Doggzone

# Build settings
markdown: kramdown
theme: minima
